Fixes #91
silviot/EisBuk pull request #111
Opened 2021-07-07 08:46 UTC by fadwamahmoud

selectable copypaste functionality:
- implemented two new actions for adding ond deleting from copyWeekSlots
- selecting a slot highlights and deselecting de-highlights
- slots can be pasted into non-empty weeks

2021-07-07 09:16 UTC, ikusteu approved these changes

2021-07-07 22:07 UTC, silviot requested changes
Great job!

I have a couple of minor requests for change, but I think in general this PR nails it.

One more minor comment: let's give descriptive titles to PRs, even if they include the ticket number in the title. It will improve the PR listing.

2021-07-07 22:07 UTC, silviot commented on eisbuk-admin/src/components/slots/SlotListByDay/SlotsDay.js
> +  const canClickSlots = enableEdit && copiedWeekSlots.length > 0;
I believe we should check on one more condition here: that the week currently displayed is the one currently in the clipboard.

With the current logic the user might select slots from two different weeks, and get surprising results on paste.

Other than this, I like the idea that, after deselecting all slots, the user needs to press the copy button again to get into "select mode".

2021-07-14 08:46 UTC, silviot approved these changes

2021-07-14 10:20 UTC, merged